image_server: https://api.elaina.cat/random/pc/

statics: "/" # 静态文件根目录，可用于 CDN 加速
assets: "assets" # 图片资源存放目录
css: "css" # css 存放目录 (不建议改动)
js: "js" # js 存放目录 (不建议改动)

experiments:
  mobileWidth: 820px # 移动版和桌面版导航栏最短切换长度
  copyrightLength: 50 # 自定义复制时显示copyright的长度
  antiFakeWebsite: false # 防止恶意网站伪装

modules:
  player: false # 启用音乐播放器
  fireworks: false # 启用鼠标点击烟花特效
  unlazyHash: false # 启用unlazy hash预览图支持
  visibilityListener: true # 启用可见度监听器
  tabs: true # 启用选项卡扩展支持，如需开启 summary 功能请一并开启
  quiz: true # 启用文章内问题扩展支持
  fancybox: true # 启用 fancybox 支持（不建议禁用）

homeConfig:
  gradient: false # 使用CSS渐变作为文章封面
  # fixedCover 性能比默认的更好，且开启时将启用LCP优化和预加载
  fixedCover: "" # 主页面cover(为空则使用bing随机图片)

menu:
  home: / || home # 独立导航项 - 首页
  文章: # 下拉菜单组
    default: /# || feather 
    归档: /archives/ || list-alt 
    标签: /tags/ || tags
    分类: /categories/ || th
  服务: 
    default: /# || zuopin 
    music: https://music.lzwxx.top || music 
    openlist: https://openlist.lzwxx.top || cloud 
  关于: /about/ || user-circle 
  友链: /friends/ || link 

social:
  github: https://github.com/zxlwl || github || "#191717"
  # google: https://plus.google.com/yourname || google
  # twitter: https://twitter.com/yourname || twitter || "#00aff0"
  # zhihu: https://www.zhihu.com/people/yourname || zhihu || "#1e88e5"
  # music: https://music.163.com/#/user/home?id=yourid || cloud-music || "#e60026"
  # weibo: https://weibo.com/yourname || weibo || "#ea716e"
  # about: https://about.me/yourname || address-card || "#3b5998"
  # email: mailto:foo@xxx.com || envelope || "#55acd5"
  # facebook: https://www.facebook.com/yourname || facebook
  # stackoverflow: https://stackoverflow.com/ || stack-overflow
  # youtube: https://youtube.com/yourname || youtube
  # instagram: https://instagram.com/yourname || instagram
  # skype: skype:yourname?call|chat || skype
  # douban: https://www.douban.com/people/yourname/ || douban

sidebar:
  position: left # left/right分别对应左侧/右侧
  avatar: avatar.jpg

widgets:
  random_posts: true # 随机文章
  recent_comments: false # 显示最近评论

# 页尾全站统计
footer:
  since: 2025 # 开始时间
  count: true # 开启
# 文章界面统计
post:
  count: true # 开启

auto_scroll: true # 自动滚动到文章内容

alternate: "Lzwxx's Blog" #站点大标题，（比 title 高一级，但仅在 index 显示）

pagefind:
  enable: true

waline:
  enable: true # 是否启用
  serverURL: "https://waline.lzwxx.top" # waline 服务端地址
  lang: "zh-CN" # 评论界面语言
  locale: {} # 本地化替换，详见 waline 文档
  emoji: # 表情包，默认为 waline 官方配置
    - https://unpkg.com/@waline/emojis@1.0.1/weibo
    - https://unpkg.com/@waline/emojis@1.0.1/alus
    - https://unpkg.com/@waline/emojis@1.0.1/bilibili
    - https://unpkg.com/@waline/emojis@1.0.1/qq
    - https://unpkg.com/@waline/emojis@1.0.1/tieba
    - https://unpkg.com/@waline/emojis@1.0.1/tw-emoji
  meta: # 评论可以填写的项目
    - nick
    - mail
    - link
  requiredMeta: # 评论必须填写的项目
    - nick
    - mail
  wordLimit: 100 # 评论字数上限 (不建议为 0)
  pageSize: 10 # 每页显示评论条数
  pageview: false # 页面浏览量显示